language: node_js
node_js:
  - "8"
env:
  - VUE_APP_CYCLOMEDIA_API_KEY=$CYCLOMEDIA_API_KEY VUE_APP_CYCLOMEDIA_PASSWORD=$CYCLOMEDIA_PASSWORD VUE_APP_CYCLOMEDIA_USERNAME=$CYCLOMEDIA_USERNAME
script: npm run build
before_deploy:
  - rm -rf node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cyclomedia.phila.gov
    skip_cleanup: true
    on:
      branch: master
