language: node_js
node_js:
  - node
script: npm run build
before_deploy:
  - rm -rf node_modules
  # - source ./.travis/s3_utils.sh
  # - S3_BUCKET=$(get_s3_bucket)s
  - echo "Will push to S3 bucket $S3_BUCKET."
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cyclomedia.phila.gov
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: atlas-dev.phila.gov
    on:
      branch: update
    local_dir: dist
    skip_cleanup: true
